version: "~> 1.0"
git:
  depth: 1
  quiet: true
language: java
jdk:
  - openjdk21
branches:
  only:
    - develop
    - support/4.x
cache:
  directories:
    - "$HOME/.m2"
notifications:
  slack: craftersoftware:7YiSb41ZG5rfMgiAY7Qgprc7
before_install:
  - mkdir -p $HOME/.m2
  - cp .travis-settings.xml $HOME/.m2/settings.xml
install: skip
script:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then bash -c "mvn deploy --settings .travis-settings.xml"; fi
  - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then bash -c "mvn clean install"; fi
env:
  global:
    - secure: "QVuMQOWgyVCkSaeoOWceWIYuRI0S8vPH2lRonjE4rxV6RuySY5IwWAAwZz4SxQ7ZuY6b5UK+SxLjI3NpTvZY7YpzEMRVQz2ph2Gcb41qWSBUFiE5lU0b+Y0iniPN2Hul/6MeiQAOn7m1hZ6ocg+B5bEJxo8KrJJFrjvUGuS2SzE="
    - secure: "J1a9C/TrK8RI5W0EpBbob+yp24kDT95QUz/jc/caqe2Y5NzcRJaKJHYauffMRDp+AlTDf0YR8WGjUEmMdSeRRY54T022VldxV4ETcCnRZoCqfStrGfb67GJyNSHncmIz9sbO/8JKzzxlDPhyWNphvLRl2bpTdVNwAOwWma8fMlM="
